name: Build SQLNA
# manually triggered workflow
on: [workflow_dispatch]
env:
    SOLUTION_FILE_PATH: .\SQL_Network_Analyzer
    BUILD_CONFIGURATION: Release
jobs:
    job1:
      runs-on: windows-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      - name: Create Build Directory
        run: mkdir _build
      - name: Build It
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /p:RunCodeAnalysis=False /p:DeleteExistingFiles=True
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: SQLNA.EXE
          path: "SQLNA\\bin\\Debug"
